spring:
  redis:
    # 单节点的ip
    # host:
    # 单节点的端口
    # port:
    cluster:
      # 集群节点
      nodes: 172.16.12.3:7000,172.16.12.3:7001,172.16.12.3:7002,172.16.12.3:7003,172.16.12.3:7004,172.16.12.3:7005
    # 连接超时时间
    timeout: 10000
    # 密码(默认是空)
    password:
    # Redis数据库索引(默认是0)
    database: 0
    jedis:
      pool:
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
        # 连接池最大连接数(使用负值表示没有限制)
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

